version: '3'

services:
  mysql:
    container_name: wordpress_mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mywordpresssite

  wordpress:
    container_name: wordpress_web
    depends_on:
      - mysql
    image: wordpress:latest
    restart: always
    ports:
      - "9080:80"
    volumes:
      # For full wordpress development
      # - ./src:/var/www/html
      # For plugin development
      - ./src/wp-content/plugins/:/var/www/html/wp-content/plugins/
      # For theme development
      - ./src/wp-content/themes/:/var/www/html/wp-content/themes/
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini 
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: mywordpresssite
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
      WORDPRESS_DB_PORT: 3306
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
volumes:
  db_data: