version: "3"

services:
  mariadb:
    container_name: maria
    image: mariadb:latest
    volumes:
      - data:/var/lib/mysql/wordpress
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: goon
      MYSQL_USER: goon
      MYSQL_DATABASE: goon
      MYSQL_PASSWORD: goon

  wordpress:
    container_name: wordpress_web
    depends_on:
      - mariadb
    image: wordpress:latest
    restart: always
    ports:
      - "9080:80"
    volumes:
      # For full wordpress development
      - ./src:/var/www/html
      # For plugin development
      - ./src/wp-content/plugins/:/var/www/html/wp-content/plugins/
      # For theme development
      - ./src/wp-content/themes/:/var/www/html/wp-content/themes/
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: goon
      WORDPRESS_DB_USER: goon
      WORDPRESS_DB_PASSWORD: goon
      WORDPRESS_DB_PORT: 3306
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.api.rule=Host(`goon.tcp`)"
    #   - "traefik.http.routers.api.entrypoints=web"
  adminer:
    image: adminer
    container_name: api-adminer
    restart: always
    links:
      - mariadb

volumes:
  data:
