version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run start
    ports:
      - '9000:9000'
    environment:
      NODE_ENV: production
