version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run start
    ports:
      - '3002:3002'
    environment:
      NODE_ENV: production
