version: "3"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: always
    ports:
      # HTTP port
      - "80:80"
      # HTTPS Port:
      - "443:443"
      # Admin UI
      - "81:81"
    environment:
      DB_SQLITE_FILE: "/data/npm.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
