version: "3.3"
services:
  traefik:
    image: "leejoneshane/scratch3"
    container_name: "sratch"
    restart: always
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.sratch.rule=Host(`coding.localhost`)"
    #   - "traefik.http.routers.sratch.entrypoints=web"
    #   - "com.centurylinklabs.watchtower.scope=sratch"
    ports:
      - "3006:80"
    networks:
      - web

networks:
  web:
    external: true
