version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    command: mongod --oplogSize 128 --replSet rs0
    volumes:
      - mongodb_data:/data/db

  mongo-init-replica:
    image: mongo:latest
    container_name: mongo_replica
    restart: on-failure
    command: 'mongo mongo/rocketchat --eval "printjson(rs.initiate())"'
    depends_on:
      - mongo

  rocketchat:
    image: rocket.chat:3
    depends_on:
      - mongo
    container_name: rocket
    restart: unless-stopped

    environment:
      - PORT=3000
      - ROOT_URL=http://message.tcp
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replSet=rs0

volumes:
  mongodb_data: { driver: local }

